export const headerItems = [
  { id: 1, label: "Home", path: "/" },
  { id: 2, label: "About", path: "/about" },
  { id: 3, label: "work", path: "/work" },
  { id: 4, label: "services", path: "/services" },
  { id: 5, label: "learn", path: "/learn" },
  { id: 6, label: "Contact", path: "/contact" },
];

export const categoryItem = [
  { id: 1, label: "all", value: "all" },
  { id: 3, label: "javascript", value: "javascript" },
  { id: 2, label: "react", value: "react" },
  { id: 4, label: "web development", value: "web_development" },
  { id: 5, label: "design", value: "design" },
  { id: 6, label: "node.js", value: "node.js" },
  { id: 7, label: "typeScript", value: "typescript" },
];

export const articles = [
  {
    id: 1,
    title: "JavaScript Utility Functions Learning Guide",
    category: "javascript",
    difficulty: "Beginner",
    date: "Jul 26, 2025",
    readTime: "15 min read",
    description:
      "Master essential JavaScript utilities with practical examples and clean implementations. Learn debounce, throttle, deep cloning and more.",
    tags: ["JavaScript", "Utilities", "Functions"],
  },
  {
    id: 2,
    title: "Mastering React Hooks",
    category: "react",
    difficulty: "Intermediate",
    date: "Aug 1, 2025",
    readTime: "20 min read",
    description:
      "Learn how to effectively use React hooks like useState, useEffect, useMemo, and custom hooks for cleaner code.",
    tags: ["React", "Hooks", "Frontend"],
  },
  {
    id: 3,
    title: "Node.js Crash Course",
    category: "node.js",
    difficulty: "Beginner",
    date: "Sep 2, 2025",
    readTime: "10 min read",
    description:
      "A beginner-friendly crash course on Node.js covering the basics of backend development and APIs.",
    tags: ["Node.js", "Backend", "APIs"],
  },
];

export const allProjects = [
  {
    id: 13,
    name: "WinnSEO APP",
    image: "/images/winnseo.png",
    author: "Media365 Limited",
    language: ["Shopify", "Remix", "Polaris", "LLM", "Tailwind CSS"],
    link: "https://apps.shopify.com/winnseo",
    creationDate: "2025",
  },
  {
    id: 3,
    name: "Nexis Limited",
    image: "/images/nexis_ltd.png",
    author: "Nexis Limited",
    language: ["NextJS", "Tailwind CSS", "TypeScript", "Django", "PostgreSQL"],
    link: "https://www.nexisltd.com/",
    creationDate: "2022",
  },
  {
    id: 12,
    name: "E-Tutor Learning Platform",
    image: "/images/e-learning.png",
    author: "Self Project",
    language: ["Angular", "TypeScript", "Tailwind CSS"],
    link: "https://e-tutor-learning.vercel.app/",
    creationDate: "2025",
  },
  {
    id: 7,
    name: "Foody Restaurant",
    author: "Self Project",
    image: "/images/foody_restaurent.png",
    language: ["NextJS", "TypeScript", "Tailwind CSS"],
    link: "https://vault-restaurent.vercel.app/",
    creationDate: "2024",
  },
  {
    id: 9,
    name: "Dream Travel Country",
    image: "/images/toursim.png",
    author: "Self Project",
    language: ["ReactJS", "Tailwind CSS", "Node.js", "Express.js", "MongoDB"],
    link: "https://tourism-eb29a.firebaseapp.com/",
    creationDate: "2021",
  },
  {
    id: 10,
    name: "Bondhu Health",
    author: "Self Project",
    language: ["ReactJS", "TypeScript", "Tailwind CSS"],
    image: "/images/bondhu-health.png",
    link: "https://bondhuhealth.netlify.app/",
    creationDate: "2022",
  },
  {
    id: 4,
    name: "HR",
    author: "Nexis Limited",
    image: "/images/hr.webp",
    language: ["NextJs", "Tailwind CSS", "Django", "MySQL"],
    link: "",
    creationDate: "2022",
  },
  {
    id: 6,
    name: "School Management System",
    author: "Nexis Limited",
    image: "/images/scl.jpg",
    language: ["NextJs", "Tailwind CSS", "Django", "MySQL"],
    link: "",
    creationDate: "2022",
  },
  {
    id: 5,
    name: "Digital Menu",
    author: "Nexis Limited",
    image: "/images/digital_menu.jpg",
    language: ["NextJs", "Tailwind CSS", "Django", "MySQL"],
    link: "",
    creationDate: "2022",
  },
];
